name: Deploy Admin to Vercel

on:
  push:
    branches: [main]
    paths:
      - 'admin/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: admin
        env:
          VERCEL_ORG_ID: team_kEgwUBBfT197TJSYk93DtoYP
          VERCEL_PROJECT_ID: prj_sHq3CD3Yopr09HYlKJ6NFs3N0TM5
